create table eventos (
       id bigint generated by default as identity,
        ordem integer,
        parametros varchar(255),
        situacao boolean,
        tela_id bigint,
        tipo_evento_id bigint,
        primary key (id)
    );

    
    create table projetos (
       id bigint generated by default as identity,
        nome varchar(255),
        situacao boolean,
        primary key (id)
    );

    
    create table propriedades (
       id bigint generated by default as identity,
        chave varchar(255),
        ordem integer,
        valor varchar(255),
        requisicao_id bigint,
        primary key (id)
    );

    
    create table requisicoes (
       id bigint generated by default as identity,
        camada varchar(255),
        descricao varchar(255),
        ordem integer,
        situacao boolean,
        uri_prod varchar(255),
        url_homolog varchar(255),
        evento_id bigint,
        requisicao_pai_id bigint,
        primary key (id)
    );

    
    create table telas (
       id bigint generated by default as identity,
        data_cadastro date,
        imagem varchar(255),
        nome_tela varchar(255),
        ordem integer,
        situacao boolean,
        url_log varchar(255),
        tela_pai_id bigint,
        versao_id bigint,
        versao_origem_id bigint,
        primary key (id)
    );

    
    create table tipo_eventos (
       id bigint generated by default as identity,
        nome varchar(255),
        situacao boolean,
        primary key (id)
    );

    
    create table versoes (
       id bigint generated by default as identity,
        data_lancamento date,
        descricao varchar(255),
        gmud varchar(255),
        numero_versao varchar(255),
        ordem integer,
        situacao boolean,
        projeto_id bigint,
        primary key (id)
    );

    
    alter table eventos 
       add constraint FKqutl1wcrq069r38t3iipt8rna 
       foreign key (tela_id) 
       references telas;

    
    alter table eventos 
       add constraint FKgrjur7bgbhju9ah0u0dke0r04 
       foreign key (tipo_evento_id) 
       references tipo_eventos;

    
    alter table propriedades 
       add constraint FKj6umxn0yk0sjbriiqa1o87r6x 
       foreign key (requisicao_id) 
       references requisicoes;

    
    alter table requisicoes 
       add constraint FK1ggedyjalfqkmrjeci719oaaw 
       foreign key (evento_id) 
       references eventos;

    
    alter table requisicoes 
       add constraint FKayydtr0dh13u6ma1g6j6sxff1 
       foreign key (requisicao_pai_id) 
       references requisicoes;



INSERT INTO PROJETOS (nome, situacao) VALUES  
('projeto 1', true), ('projeto 2', true);

INSERT INTO VERSOES 
(gmud, descricao, data_lancamento, situacao, ordem, numero_versao, projeto_id)
values
('123456', 'versao beta', '2021-07-01', true, 2, '0.1', 1),
('46516', 'versao final', '2021-08-01', true, 1, '1.0', 1),
('46846', 'versao beta', '2020-07-05', false, 3, '0.1', 2)
;

INSERT INTO TELAS 
(versao_id, data_cadastro, nome_tela, imagem, situacao, tela_pai_id,
ordem, url_log, versao_origem_id)
values 
(1, '2021-07-01', 'Tela A', 'imagem da tela', true, null,
1, 'http://urlLog.com', 1),
(1, '2020-07-01', 'Tela B', 'foot', true, null,
2, 'http://urlLogasfas.com', 1)
;  

INSERT INTO TIPO_EVENTOS
(NOME, SITUACAO)
VALUES
('onClick', true),
('onLoad', true);

INSERT INTO EVENTOS
(SITUACAO, ORDEM, PARAMETROS, TELA_ID, TIPO_EVENTO_ID)
VALUES
(true, 1, 'login, senha', 1, 1),
(true, 2, 'email, senha', 1, 1); 

INSERT INTO REQUISICOES
(CAMADA, DESCRICAO, ORDEM, URL_HOMOLOG, EVENTO_ID,
REQUISICAO_PAI_ID, URI_PROD, SITUACAO)
VALUES
('barramento', 'descricao da camada', 1 ,'urlHomolog.com',
1, null, 'uriProd.com', true);
